"""
--------------------------------------------------------------------------------
FILE:        dga.py
PATH:        ~/projects/pihole-watch/pihole_watch/dga.py
DESCRIPTION: Heuristic DGA (domain generation algorithm) classifier. No model
             file -- features are computed on the leftmost label with TLDs
             (and known multi-part suffixes) trimmed, then summed into a
             0.0-1.0 score. Allowlist short-circuits common cloud/CDN
             generated names that look DGA-like.

CHANGELOG:
2026-04-25            Claude      [Feature] Initial implementation.
--------------------------------------------------------------------------------
"""

from __future__ import annotations

import math
import re
from collections import Counter

# Hostnames whose left-labels are auto-generated by clouds / CDNs and look
# DGA-like but are legitimate. Match on suffix.
_ALLOWLIST_SUFFIXES: tuple[str, ...] = (
    ".amazonaws.com",
    ".cloudfront.net",
    ".azureedge.net",
    ".googleusercontent.com",
    ".fastly.net",
    ".cdn-cgi.com",
    ".appspot.com",
    ".github.io",
    ".akamai.net",
    ".akamaiedge.net",
    ".akamaihd.net",
    ".akamaized.net",
    ".edgekey.net",
    ".edgesuite.net",
    ".cdn.cloudflare.net",
    ".trafficmanager.net",
    ".windows.net",
    ".herokuapp.com",
)

# Multi-label public suffixes we should strip before scoring the registrable
# label. Keep this small -- accuracy doesn't require a full PSL.
_MULTI_PART_SUFFIXES: tuple[str, ...] = (
    "co.uk", "ac.uk", "gov.uk", "org.uk",
    "com.au", "net.au", "org.au", "edu.au",
    "co.jp", "ne.jp", "ac.jp",
    "co.nz", "co.kr", "co.in", "co.za",
    "com.br", "com.mx", "com.ar",
    "com.cn", "com.hk", "com.tw", "com.sg",
)

_VOWELS = set("aeiou")
_LETTER_RE = re.compile(r"[a-z]")


def _is_allowlisted(domain: str) -> bool:
    d = domain.lower().strip(".")
    for suffix in _ALLOWLIST_SUFFIXES:
        if d.endswith(suffix):
            return True
    return False


def _registrable_label(domain: str) -> str:
    """Return the leftmost meaningful label of a domain after stripping the TLD
    (and known multi-part public suffixes).

    Examples:
        google.com           -> google
        api.stripe.com       -> api
        foo.bar.co.uk        -> foo
        xnvbq3mlpoq.evil.com -> xnvbq3mlpoq
    """
    d = domain.lower().strip(".")
    if not d:
        return ""
    # Strip multi-part suffixes first
    for suf in _MULTI_PART_SUFFIXES:
        dotted = "." + suf
        if d.endswith(dotted):
            d = d[: -len(dotted)]
            break
    parts = d.split(".")
    if len(parts) >= 2:
        # Drop the TLD (last part); leftmost label is parts[0]
        return parts[0]
    return parts[0]


def _shannon_entropy(s: str) -> float:
    if not s:
        return 0.0
    counts = Counter(s)
    n = len(s)
    return -sum((c / n) * math.log2(c / n) for c in counts.values())


def _max_consonant_run(s: str) -> int:
    longest = 0
    cur = 0
    for ch in s:
        if ch.isalpha() and ch not in _VOWELS:
            cur += 1
            if cur > longest:
                longest = cur
        else:
            cur = 0
    return longest


def domain_features(domain: str) -> dict[str, float]:
    """Compute DGA-relevant features on the leftmost label of ``domain``.

    Returns a dict with: length, entropy, vowel_ratio, max_consonant_run,
    digit_ratio, distinct_char_ratio.
    """
    label = _registrable_label(domain)
    n = len(label)
    if n == 0:
        return {
            "length": 0.0, "entropy": 0.0, "vowel_ratio": 0.0,
            "max_consonant_run": 0.0, "digit_ratio": 0.0,
            "distinct_char_ratio": 0.0,
        }

    letters = [c for c in label if c.isalpha()]
    n_letters = len(letters)
    vowel_ratio = (
        sum(1 for c in letters if c in _VOWELS) / n_letters if n_letters else 0.0
    )
    digit_ratio = sum(1 for c in label if c.isdigit()) / n
    distinct_char_ratio = len(set(label)) / n
    entropy = _shannon_entropy(label)
    max_run = _max_consonant_run(label)

    return {
        "length": float(n),
        "entropy": float(entropy),
        "vowel_ratio": float(vowel_ratio),
        "max_consonant_run": float(max_run),
        "digit_ratio": float(digit_ratio),
        "distinct_char_ratio": float(distinct_char_ratio),
    }


def dga_score(domain: str) -> float:
    """Return a 0.0-1.0 DGA-likelihood score for ``domain``.

    Allowlisted CDN/cloud suffixes short-circuit to 0.0. Otherwise the score
    is a normalized weighted sum of feature contributions; threshold tuning
    happens at the caller (typically 0.65).
    """
    if _is_allowlisted(domain):
        return 0.0

    feats = domain_features(domain)
    label_len = feats["length"]
    if label_len == 0:
        return 0.0
    if label_len < 6:
        # Very short labels (mail, api, www, cdn, ...) are noisy and almost
        # never DGA. Skip scoring.
        return 0.0

    score = 0.0

    entropy = feats["entropy"]
    vowel_ratio = feats["vowel_ratio"]
    digit_ratio = feats["digit_ratio"]
    max_run = feats["max_consonant_run"]
    distinct = feats["distinct_char_ratio"]

    # Entropy: typical English-ish labels ~2.5-3.2; DGA often >= 3.2.
    if entropy >= 3.8:
        score += 0.30
    elif entropy >= 3.4:
        score += 0.22
    elif entropy >= 3.1:
        score += 0.10

    # Length: DGA labels often 10-25 chars. Very long random labels are
    # extra suspicious.
    if 10 <= label_len <= 25:
        score += 0.18
    elif label_len > 25:
        score += 0.28
    elif label_len >= 8:
        score += 0.05

    # Vowel ratio: real English words ~0.38-0.45. DGA labels often <0.25.
    if vowel_ratio < 0.10:
        score += 0.25
    elif vowel_ratio < 0.20:
        score += 0.18
    elif vowel_ratio < 0.28:
        score += 0.08

    # Long consonant runs are unnatural in real names.
    if max_run >= 5:
        score += 0.22
    elif max_run >= 4:
        score += 0.12

    # DGA labels often mix digits and letters. The 5-40% band is the sweet
    # spot, but very heavy digit content (e.g. q1w2e3r4...) is also DGA-ish.
    if 0.05 <= digit_ratio <= 0.40:
        score += 0.18
    elif digit_ratio > 0.40:
        score += 0.22

    # Very high distinct-char ratio (each char unique) is typical of random.
    if distinct >= 0.85 and label_len >= 10:
        score += 0.10

    # Discriminator: legit English-like labels can clear the length+vowel
    # bars and bleed into 0.4-0.5 territory. Require at least one *strong*
    # DGA signal -- high entropy, very low vowel ratio, long consonant run,
    # or significant digit content -- before scoring above ~0.50.
    has_strong_signal = (
        entropy >= 3.4
        or vowel_ratio < 0.20
        or max_run >= 4
        or digit_ratio >= 0.05
    )
    if not has_strong_signal:
        score = min(score, 0.30)

    # Second-stage discriminator: a label with a normal English vowel ratio
    # (>= 0.30), no digits, and no long consonant runs is overwhelmingly
    # likely to be a real word, even if entropy and length push it up.
    # Cap such labels well below the typical flag threshold.
    looks_word_like = (
        vowel_ratio >= 0.30
        and digit_ratio < 0.05
        and max_run < 4
    )
    if looks_word_like:
        score = min(score, 0.25)

    # Clamp to [0, 1]
    if score > 1.0:
        score = 1.0
    if score < 0.0:
        score = 0.0
    return float(score)


__all__ = ["dga_score", "domain_features"]
